# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: []
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    labels: []
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels: []
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    labels: []
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"
