# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[cargo] "
    groups:
      non-major-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[npm] "
    groups:
      non-major-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[github-actions] "
    groups:
      non-major-dependencies:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    labels: []
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[pip] "
    groups:
      non-major-dependencies:
        update-types:
          - "minor"
          - "patch"
