#
# See full list of configuration options at https://pnpm.io/settings
#

packages:
  - "crates/solidity/outputs/npm/package"
  - "crates/solidity/outputs/npm/tests"
  - "crates/solidity/testing/perf/npm"
  - "documentation/public/user-guide"

catalog:
  "@bytecodealliance/preview2-shim": "^0.17.2"
  "@changesets/changelog-github": "^0.5.1"
  "@changesets/cli": "^2.29.4"
  "@ignored/slang-jco": "^1.9.1-slang.1"
  "@openzeppelin/contracts": "^5.2.0"
  "@solidity-parser/parser": "^0.20.1"
  "@types/command-line-args": "^5.2.3"
  "@types/command-line-usage": "^5.0.4"
  "@types/jest": "^29.5.14"
  "@types/node": "^24.0.8"
  "command-line-args": "^6.0.1"
  "command-line-usage": "^7.0.3"
  "cspell": "^9.1.2"
  "jest": "^29.7.0"
  "markdown-link-check": "^3.12.2"
  "markdownlint-cli": "^0.45.0"
  "prettier-plugin-sh": "^0.17.4"
  "prettier": "^3.5.3"
  "solc": "^0.8.29"
  "ts-jest-resolver": "^2.0.1"
  "ts-jest": "^29.3.4"
  "tsx": "^4.19.4"
  "typedoc": "^0.28.5"
  "typescript": "^5.8.3"

# Dependency Resolution
minimumReleaseAge: 10080 # 1 week

# CLI Settings
npmPath: "./bin/npm"
engineStrict: true
packageManagerStrictVersion: true

# Build Settings
ignoreScripts: true
ignoreDepScripts: true
verifyDepsBeforeRun: "error"
strictDepBuilds: true

# Other Settings
catalogMode: "strict"
cleanupUnusedCatalogs: true
