[package]
name = "codegen_runtime_npm_package"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

description = "TypeScript runtime copied over by codegen"

[lints]
workspace = true
